# Workflox to run pytest when code is pushed or a pull request is created
name: flaskr

# Controls when the action will run, triggers the workflow on all pushes
on: [push]
#   push:
#     branches:
#       - main
#   pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.9 ]
        poetry: [ 1.1.13 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install poetry==${{ matrix.poetry }}
          python -m poetry install
      - name: Run pytest
        run: python -m pytest
